const allTovar = [
  {
    name: 'Палатка «Альпинист» 3-местная',
    description: 'Лёгкая палатка для горных походов, водостойкая ткань 3000 мм.',
    price: 12990,
    rating: 4.8,
    category: 'Палатки',
    emoji: '⛺',
    color: '#2d6a4f',
  },
  {
    name: 'Рюкзак TrekPro 65L',
    description: 'Эргономичная спинка, поясной ремень, отделение для гидратора.',
    price: 8490,
    rating: 4.7,
    category: 'Рюкзаки',
    emoji: '🎒',
    color: '#40916c',
  },
  {
    name: 'Спальный мешок Arctic -5°C',
    description: 'Утеплитель синтетический, компактный чехол в комплекте.',
    price: 5990,
    rating: 4.5,
    category: 'Сон',
    emoji: '🛏️',
    color: '#1b4332',
  },
  {
    name: 'Коврик туристический NeoRest',
    description: 'Надувной коврик с изоляцией R-value 4.2, вес 450 г.',
    price: 4290,
    rating: 4.6,
    category: 'Сон',
    emoji: '🧘',
    color: '#52b788',
  },
  {
    name: 'Трекинговые ботинки TrailMax',
    description: 'Мембрана Gore-Tex, Vibram-подошва, поддержка голеностопа.',
    price: 11490,
    rating: 4.9,
    category: 'Обувь',
    emoji: '🥾',
    color: '#6c584c',
  },
  {
    name: 'Кроссовки для трейлраннинга',
    description: 'Лёгкие, с агрессивным протектором и усиленным носком.',
    price: 7990,
    rating: 4.4,
    category: 'Обувь',
    emoji: '👟',
    color: '#a98467',
  },
  {
    name: 'Куртка Softshell WindGuard',
    description: 'Ветрозащита, эластичная ткань, капюшон и карманы на молнии.',
    price: 9490,
    rating: 4.6,
    category: 'Одежда',
    emoji: '🧥',
    color: '#354f52',
  },
  {
    name: 'Флисовая кофта PolarLite',
    description: 'Быстросохнущий флис, удобна как средний слой.',
    price: 3490,
    rating: 4.3,
    category: 'Одежда',
    emoji: '👕',
    color: '#52796f',
  },
  {
    name: 'Штаны трансформеры Convert',
    description: 'Отстёгивающиеся штанины, UPF 50+, 6 карманов.',
    price: 4990,
    rating: 4.2,
    category: 'Одежда',
    emoji: '👖',
    color: '#588157',
  },
  {
    name: 'Компас Silva Ranger',
    description: 'Жидкостный компас с линейкой и declination adjustment.',
    price: 2890,
    rating: 4.7,
    category: 'Навигация',
    emoji: '🧭',
    color: '#bc6c25',
  },
  {
    name: 'GPS-навигатор Garmin eTrex',
    description: 'Поддержка GLONASS/GPS, карты топо, 25 ч автономности.',
    price: 18990,
    rating: 4.8,
    category: 'Навигация',
    emoji: '📡',
    color: '#dda15e',
  },
  {
    name: 'Фонарь налобный UltraBeam 800',
    description: '800 люмен, USB-C зарядка, красный режим для ночи.',
    price: 3190,
    rating: 4.5,
    category: 'Свет',
    emoji: '🔦',
    color: '#283618',
  },
  {
    name: 'Кемпинговый фонарь SolarLantern',
    description: 'Складной, солнечная панель, 3 режима яркости.',
    price: 2490,
    rating: 4.1,
    category: 'Свет',
    emoji: '🏮',
    color: '#606c38',
  },
  {
    name: 'Горелка газовая PocketStove',
    description: 'Компактная, мощность 2800 Вт, piezo-поджиг.',
    price: 2190,
    rating: 4.6,
    category: 'Кухня',
    emoji: '🔥',
    color: '#e76f51',
  },
  {
    name: 'Набор посуды CampCook 4',
    description: 'Кастрюля, сковорода, 2 кружки, ложки — всё в одном мешке.',
    price: 3790,
    rating: 4.4,
    category: 'Кухня',
    emoji: '🍳',
    color: '#f4a261',
  },
  {
    name: 'Термос SteelVac 1L',
    description: 'Держит тепло 18 ч, нержавеющая сталь, без BPA.',
    price: 2690,
    rating: 4.7,
    category: 'Кухня',
    emoji: '🫖',
    color: '#264653',
  },
  {
    name: 'Фильтр для воды LifeStraw',
    description: 'Очищает до 4000 л, убирает 99.9% бактерий.',
    price: 3290,
    rating: 4.8,
    category: 'Кухня',
    emoji: '💧',
    color: '#2a9d8f',
  },
  {
    name: 'Трекинговые палки Carbon Pair',
    description: 'Углеродные палки, быстрый клип-лок, пробковые ручки.',
    price: 5490,
    rating: 4.5,
    category: 'Аксессуары',
    emoji: '🦯',
    color: '#457b9d',
  },
  {
    name: 'Сиденье туристическое FoldSeat',
    description: 'Складное, с термоизоляцией от холодной земли.',
    price: 890,
    rating: 4.0,
    category: 'Аксессуары',
    emoji: '🪑',
    color: '#1d3557',
  },
  {
    name: 'Мультитул TrailTool 18',
    description: '18 функций: нож, плоскогубцы, открывалка, пила.',
    price: 4590,
    rating: 4.6,
    category: 'Аксессуары',
    emoji: '🔧',
    color: '#495057',
  },
  {
    name: 'Аптечка первой помощи TravelMed',
    description: '45 позиций: пластыри, антисептик, бинты, таблетки.',
    price: 1990,
    rating: 4.7,
    category: 'Безопасность',
    emoji: '🩹',
    color: '#e63946',
  },
  {
    name: 'Свисток сигнальный Storm',
    description: '120 дБ, работает даже при намокании.',
    price: 390,
    rating: 4.2,
    category: 'Безопасность',
    emoji: '📣',
    color: '#f77f00',
  },
  {
    name: 'Powerbank Solar 20000 mAh',
    description: 'Солнечная зарядка, 2 USB-A + USB-C, защита IP65.',
    price: 4990,
    rating: 4.3,
    category: 'Электроника',
    emoji: '🔋',
    color: '#023047',
  },
  {
    name: 'Экшн-камера AdventureCam 4K',
    description: '4K 30fps, стабилизация, водонепроницаемый кейс.',
    price: 14990,
    rating: 4.5,
    category: 'Электроника',
    emoji: '📷',
    color: '#219ebc',
  },
  {
    name: 'Портативная колонка RockOut',
    description: '12 ч звучания, Bluetooth 5.0, карабин для рюкзака.',
    price: 3990,
    rating: 4.1,
    category: 'Электроника',
    emoji: '🔊',
    color: '#8ecae6',
  },
  {
    name: 'Гамак TravelNest Double',
    description: 'Парашютная нейлоновая ткань, до 180 кг, стропы в комплекте.',
    price: 3490,
    rating: 4.4,
    category: 'Отдых',
    emoji: '🪢',
    color: '#386641',
  },
  {
    name: 'Тент-тarp UltraLight 3×3',
    description: 'Универсальный тент, 8 точек крепления, 420 г.',
    price: 4290,
    rating: 4.3,
    category: 'Палатки',
    emoji: '🏕️',
    color: '#6a994e',
  },
  {
    name: 'Спальник-пододеяло DownLite 600',
    description: 'Пух 600 FP, температурный режим до -10°C, 780 г.',
    price: 13990,
    rating: 4.9,
    category: 'Сон',
    emoji: '🌙',
    color: '#344e41',
  },
  {
    name: 'Dry Bag набор 3 шт',
    description: '5L / 10L / 20L, герметичные, яркие цвета для видимости.',
    price: 1590,
    rating: 4.5,
    category: 'Аксессуары',
    emoji: '🎒',
    color: '#0077b6',
  },
  {
    name: 'Крем от солнца SPF 50+ Sport',
    description: 'Водостойкий, не оставляет следов, 100 мл.',
    price: 790,
    rating: 4.2,
    category: 'Гигиена',
    emoji: '🧴',
    color: '#ffb703',
  },
  {
    name: 'Набор быстрой сушки TravelKit',
    description: 'Полотенце, мыло, шампунь — всё в компактных флаконах.',
    price: 1290,
    rating: 4.0,
    category: 'Гигиена',
    emoji: '🧼',
    color: '#fb8500',
  },
  {
    name: 'Бинокль CompactView 10×42',
    description: 'Просветлённые линзы, резиновое покрытие, ремешок.',
    price: 8990,
    rating: 4.6,
    category: 'Навигация',
    emoji: '🔭',
    color: '#03045e',
  },
  {
    name: 'Кемпинговый стул TripChair',
    description: 'Складной, алюминиевая рама, 120 кг нагрузка, 900 г.',
    price: 2790,
    rating: 4.3,
    category: 'Отдых',
    emoji: '🪑',
    color: '#780000',
  },
  {
    name: 'Плащ-дождевик RainShield Pro',
    description: 'Полностью водонепроницаемый, вентиляционные молнии.',
    price: 2190,
    rating: 4.4,
    category: 'Одежда',
    emoji: '🌧️',
    color: '#0077b6',
  },
].map((item, key) => ({ ...item, key }))
